[project]
name = "vlarl-infra"
version = "0.1.0"
description = ""
authors = [
    {name = "chenhao lu",email = "luch21@mails.tsinghua.edu.cn"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "loguru (>=0.7.3,<0.8.0)",
    "gymnasium (>=1.2.0,<2.0.0)",
    "dm-tree (>=0.1.9,<0.2.0)",
    "websockets (>=15.0.1,<16.0.0)",
    "msgpack (>=1.1.1,<2.0.0)",
    "tyro (>=0.9.31,<0.10.0)",
    "vlarl-client @ git+https://github.com/CTP314/vlarl-client.git",
    "pandas (>=2.3.3,<3.0.0)",
]

[tool.poetry]
packages = [{include = "vlarl_infra", from = "src"}]

[tool.poetry.scripts]
vlarl-run-worker = "vlarl_infra.cli:main"

[tool.poetry.dependencies]

[tool.poetry.group.robomimic.dependencies]
cython = "<3"
d4rl = "^1.1"
patchelf = "^0.17.2.4"
robomimic = "0.3.0"
robosuite = "<1.5.0"
pyopengl = "3.1.4"


[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"


[tool.poetry.group.atari.dependencies]
ale-py = "0.9"
gymnasium = {extras = ["atari"], version = "^1.2.1"}


[tool.poetry.group.classic.dependencies]
gymnasium = {extras = ["classic-control"], version = "^1.2.1"}



[tool.poetry.group.d4rl.dependencies]
cython = "<3"
d4rl = "^1.1"
patchelf = "^0.17.2.4"
gymnasium-robotics = {extras = ["mujoco-py"], version = "^1.4.1"}



[tool.poetry.group.libero.dependencies]
libero = {git = "https://github.com/CTP314/LIBERO.git"}

[[tool.poetry.source]]
name = "mirrors"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
priority = "primary"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
